
/**
* LibraryService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LibraryServicesInterface.idl
* Tuesday, February 26, 2019 5:30:04 PM EST
*/

public interface LibraryService extends LibraryServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LibraryService
