
/**
* LibraryServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LibraryServicesInterface.idl
* Tuesday, February 26, 2019 10:02:20 o'clock PM EST
*/

public interface LibraryServiceOperations 
{
  String findItem (String userId, String itemName);
  String returnItem (String userId, String itemID);
  String borrowItem (String userId, String itemID, int numberOfDays);
  String addItem (String userId, String itemID, String itemName, int quantity);
  String removeItem (String managerId, String itemId, int quantity);
  String listItem (String managerId);
  String addUserInWaitingList (String userId, String ItemId, int numberOfDays);
} // interface LibraryServiceOperations
