
/**
* LibraryService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from LibraryServicesInterface.idl
* Monday, March 4, 2019 2:29:33 o'clock PM EST
*/

public interface LibraryService extends LibraryServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface LibraryService
